---
- name: Build, tag, push Docker image, and run container
  hosts: localhost
  become: yes
  become_method: sudo
  vars:
    docker_image_name: simple-web
    docker_tag: latest
    docker_context_dir: /home/jenkins/workspace/simple-web-app/docker
    dockerfile_name: dockerfile
    container_name: simple-web
    container_port: 80
    host_port: 80
    dockerhub_username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
    dockerhub_password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"

  tasks:
    - name: Ensure DockerHub credentials are provided via environment
      assert:
        that:
          - dockerhub_username is defined and dockerhub_username | length > 0
          - dockerhub_password is defined and dockerhub_password | length > 0
        fail_msg: "DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD must be provided via Jenkins credentials."

    - name: Ensure Docker is available
      command: docker --version

    - name: Docker login to Docker Hub
      command: >-
        docker login -u {{ dockerhub_username }} -p {{ dockerhub_password }}
      no_log: true

    - name: Build Docker image from Jenkins workspace docker directory
      command: >-
        docker build
        -t {{ dockerhub_username }}/{{ docker_image_name }}:{{ docker_tag }}
        -f {{ dockerfile_name }}
        .
      args:
        chdir: "{{ docker_context_dir }}"

    - name: Push Docker image to Docker Hub
      command: docker push {{ dockerhub_username }}/{{ docker_image_name }}:{{ docker_tag }}

    - name: Stop and remove existing container if running
      shell: |
        docker rm -f {{ container_name }} 2>/dev/null || true
      args:
        executable: /bin/bash

    - name: Run container and keep it running
      command: >-
        docker run -d --name {{ container_name }}
        -p {{ host_port }}:{{ container_port }}
        --restart unless-stopped
        {{ dockerhub_username }}/{{ docker_image_name }}:{{ docker_tag }}
