pipeline {
  agent { label 'slave' }

  options {
    timestamps()
  }

  stages {
    stage('Checkout') {
      steps {
        git branch: 'master',
            credentialsId: 'github',
            url: 'https://github.com/rozana10710/demo2-jenkins-ansbile-docker-webapp.git'
        sh 'git log -1 --oneline || true'
      }
    }
  }
}
